CREATE TABLE departments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR(100) NOT NULL,
    department_phone VARCHAR(30) NOT NULL,
    department_email VARCHAR(100) NOT NULL,
    head_id INTEGER
);

CREATE TABLE positions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_name VARCHAR(100) NOT NULL,
    position_salary DECIMAL(12, 2) NOT NULL
);

CREATE TABLE employees (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    department_id INTEGER NOT NULL,
    position_id INTEGER NOT NULL,

    CONSTRAINT fk_employee_department
        FOREIGN KEY (department_id)
        REFERENCES departments(id),

    CONSTRAINT fk_employee_position
        FOREIGN KEY (position_id)
        REFERENCES positions(id)
);

ALTER TABLE departments
ADD CONSTRAINT fk_department_head
FOREIGN KEY (head_id)
REFERENCES employees(id);