CREATE TABLE departments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR(100) NOT NULL,
    department_phone VARCHAR(20) NOT NULL,
    department_email VARCHAR(100) NOT NULL
);

CREATE TABLE positions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_name VARCHAR(100) NOT NULL,
    position_salary DECIMAL(12, 2) NOT NULL
);

CREATE TABLE employees (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    department_id INTEGER NOT NULL,
    position_id INTEGER NOT NULL,
    is_department_head SMALLINT DEFAULT 0 NOT NULL,

    CONSTRAINT fk_employee_department
        FOREIGN KEY (department_id)
        REFERENCES departments(id),

    CONSTRAINT fk_employee_position
        FOREIGN KEY (position_id)
        REFERENCES positions(id),

    CONSTRAINT chk_employee_head
        CHECK (is_department_head IN (0, 1))
);